### ISSUE TITLE
BOM in gdb commands

### ISSUE THREAD

**Issue by service-trade** [llucenic/MonoDevelop.Debugger.Gdb.D#3]
When I'm try to debug D application I getting error:

MonoDevelop.Debugger.Gdb.GdbException: Undefined command: "".  
Try "help".
  at MonoDevelop.Debugger.Gdb.GdbSession.RunCommand 
(System.String command, System.String[] args) [0x00000] in 
<filename unknown>:0
  at MonoDevelop.Debugger.Gdb.GdbSession.OnRun 
(Mono.Debugging.Client.DebuggerStartInfo startInfo) [0x00000] in 
<filename unknown>:0
  at 
Mono.Debugging.Client.DebuggerSession+<Run>c__AnonStorey6.<>m__3 
() [0x00000] in <filename unknown>:0

And in Application Output window:

\357\273\277-inferior-tty-set /dev/pts/2
Undefined command: \"\".  Try \"help\".

Where \357\273\277 is unicode byte order mark.

The same result i'm got when created and run "hello world" C 
console project. When I disabled plugin everything went ok.

MonoDevelop 4.2.3 under Arch Linux

Mono-D 1.6.7 & D gdb debug plugin 0.2.6

**Comment by aBothe** [comment]
Very strange behaviour. With my normal setup, everything does work as normal.
Which gdb version do you've got installed? Normally, no BOM should be written to gdb's stdin.

**Comment by service-trade** [comment]
I think it was occured after last update.
May be russian utf-8 locale gives trouble?

**Comment by aBothe** [comment]
It's not happening with the german one (although I'm not sure whether it's set to treat each thing as german input) - or..I don't know what's required to get such code.

**Comment by service-trade** [comment]
Updated to 4.2.4 -- same error
Executed under root -- same error

**Comment by service-trade** [comment]
Anyway the problem exists. And exists not only with D projects. When I disable plugin -- debug runs with out problems (on C projects)

**Comment by aBothe** [comment]
Hmm. I can't find any place where it's sending such a thing (explicitly).

When you disable the debug addin - will a C project still be getting debugged properly? If not, then it's some strange and rare internal issue I don't know anything about. [Edit: Ah, you mentioned that it works before]

**Comment by aBothe** [comment]
Well in that case..I feel like I can't do anything about this issue, simply as I have no idea on how to reproduce it. Sorry about that.

**Comment by service-trade** [comment]
When I disabling this plugin debug works properly, without such error, on C projects.

**Comment by service-trade** [comment]
So I think BOM is written definitely by plugin. How to switch on logging?

**Comment by aBothe** [comment]
You have to set the env var MONODEVELOP_GDB_LOG before executing MonoDevelop or define  a property called LogGdb in the MonoDevelop config that has the value 'true'.

**Comment by service-trade** [comment]
Where to find the log file? I don't see it output in ~/.cache/MonoDevelop-4.0/Logs/Ide.log

**Comment by aBothe** [comment]
Hmm, I can't see it either..meh.

**Comment by service-trade** [comment]
What version of mono platform are you using? Mine is 3.2.3-2
Problem is in StartGdb() when it creates 'sin' BOM is written to it before first call to RunCommand()

**Comment by aBothe** [comment]
My mono version is 3.2.7 - I've built it recently.
http://simendsjo.me/files/abothe/ - you may try this bundle (mono + monodevelop is already in there, you have to untar it to /opt/mono - then you can launch MD via /opt/mono/bin/monodevelop

**Comment by service-trade** [comment]
Ok I try.
And what version of GDB you're using?

**Comment by aBothe** [comment]
7.7

**Comment by service-trade** [comment]
I'm too... hmm.
Are you using UTF-8 or single byte german locale in system? (Mine is RU_ru.UTF-8)

**Comment by aBothe** [comment]
where could I examine this info?

**Comment by service-trade** [comment]
I installed your package tried to debug and got this message:

Couldn't inject exception handler breakpoint - no finddata symbol found!warning: Could not load shared library symbols for linux-gate.so.1.\nDo you need \"set solib-search-path\" or \"set sysroot\

**Comment by service-trade** [comment]
printenv LANG
in console

**Comment by aBothe** [comment]
Alright, so it's actually able to run it properly now. The exception which pops up now is likely related to 1) linking in phobos as a shared object or 2) having some probably too old or to recent version of dmd.

**Comment by aBothe** [comment]
mine is de_DE.utf-8

**Comment by service-trade** [comment]
All looking the same but doesn't works :(

**Comment by service-trade** [comment]
And seems that is problem in Mono.

**Comment by aBothe** [comment]
but it's not breaking at the very first -inferior-tty-set anymore, right?

**Comment by service-trade** [comment]
Is gdb need some support for monodevelop?

**Comment by aBothe** [comment]
Not that I knew of. MonoDevelop's native debugger is just a gdb wrapper, nothing else. Is your gdb supporting the mi2 CLI interface?

**Comment by service-trade** [comment]
It breaks in StartGdb() when creating Process for GDB when opening standart input stream it writes BOM to it. And then when next RunCommand executed I getting error.

**Comment by service-trade** [comment]
But why then the native debugger just works in my system?
How to check that it supports mi2 ?

**Comment by service-trade** [comment]
It's supports mi2 as I see.

**Comment by service-trade** [comment]
Since it's supports it, then gdb processes command when it get newline character
StartGdb() writes BOM (in \xxx\yyy\zzz encoded form) without \n and then in RunCommand you call sin.WriteLn() with inferior and gdb gets new line, after that gdb interpret this input line and I getting error about unknown command.

**Comment by service-trade** [comment]
BOM is written in StartGdb() I'm sure. It written deeper in Mono when it processes Process constructor and creating stream object for standard input of GDB.

**Comment by aBothe** [comment]
Sure, but err, there's no explicit write command or so that invokes any BOM writing..
my log tells me:

```
INFO [2014-02-25 05:27:21Z]: Unicode (UTF-8)
INFO [2014-02-25 05:27:21Z]: gdb<: -inferior-tty-set /dev/pts/1
INFO [2014-02-25 05:27:21Z]: dbg>: =thread-group-added,id="i1"
```

**Comment by aBothe** [comment]
Please download this file: http://mono-d.alexanderbothe.com/MonoDevelop.Debugger.Gdb.D.dll
, search for the equally named file in your ~/.config or .cache folder and replace it by the new one. Then you'll get all the commands dumped as well. In theory, all the stuff had to be the same. Did you build mono on your own/installed stuff like mono-git?

**Comment by service-trade** [comment]
Same thing:

   at MonoDevelop.Ide.IdeApp.Run()
   at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options)
   at MonoDevelop.Ide.IdeStartup.Main(System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer)
   at MonoDevelop.Startup.MonoDevelopMain.Main(System.String[] args)
INFO [2014-02-25 16:17:36Z]: Unicode (UTF-8)
INFO [2014-02-25 16:17:36Z]: gdb<: -inferior-tty-set /dev/pts/5
INFO [2014-02-25 16:17:37Z]: dbg>: =thread-group-added,id="i1"
INFO [2014-02-25 16:17:37Z]: dbg>: (gdb) 
INFO [2014-02-25 16:17:37Z]: dbg>: &"\357\273\277-inferior-tty-set /dev/pts/5\n"
INFO [2014-02-25 16:17:37Z]: dbg>: &"Undefined command: \"\".  Try \"help\".\n"
INFO [2014-02-25 16:17:37Z]: dbg>: ^error,msg="Undefined command: \"\".  Try \"help\"."
INFO [2014-02-25 16:17:37Z]: dbg>: (gdb) 
ERROR [2014-02-25 16:17:37Z]: Error in debugger
MonoDevelop.Debugger.Gdb.GdbException: Undefined command: "".  Try "help".
  at MonoDevelop.Debugger.Gdb.GdbSession.RunCommand (System.String command, System.String[] args) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Debugger.Gdb.GdbSession.OnRun (Mono.Debugging.Client.DebuggerStartInfo startInfo) [0x00000] in <filename unknown>:0 
  at Mono.Debugging.Client.DebuggerSession+<Run>c__AnonStorey6.<>m__3 () [0x00000] in <filename unknown>:0

**Comment by service-trade** [comment]
I'm sure that BOM inserted in StartGdb() since if you insert sin.writeln('TEST') right after it you get:

"\357\273\277TEST\n"

**Comment by service-trade** [comment]
When Mono creates stream for redirecting standard input it's using Console.Out.Encoding

https://github.com/mono/mono/blob/master/mcs/class/System/System.Diagnostics/Process.cs

**Comment by service-trade** [comment]
Inserted after StartGdb() call  to 
sin.WriteLn(Console.Out.Encoding.ToString()); 
and got 

\357\273\277System.Text.UTF8Encoding

**Comment by aBothe** [comment]
Okay, please download the dll again. I've overwritten the Console.Out encoding now (hoping that this will affect the stdin stream generation)

**Comment by service-trade** [comment]
I downloaded by previous link and it don't help :(
Same error
\357\273\277-inferior-tty-set /dev/pts/2
Undefined command: \"\".  Try \"help\".

**Comment by aBothe** [comment]
In theory, it had to take my non-BOM encoding and apply it to the console output's stream temporarily. Can't imagine why it's still emitting it.

**Comment by service-trade** [comment]
I'm too. May be problem in low level libraries since all seems the same.
I think I need to build latest mono and monodevelop myself...

**Comment by service-trade** [comment]
I try to make new clear archlinux VM and try under it.

**Comment by service-trade** [comment]
It's not specific to your project.
If I complitely uninstall your plugin
And installed package monodevelop-debugger-gdb which appeared as GDB Support for Mono.Debugging plugin
I got the same error 1:1

**Comment by aBothe** [comment]
What I'd also like to know - is it already emitting the bom on my machine and gdb might be able to skip it? Or is it emitting it by a wrong environment configuration? I mean, even if you tried my mono build (which definitely should work on all Linuxes) it's having this issue - so it must be some very awful detail which makes the difference

**Comment by service-trade** [comment]
I tried your package mono+modevelop and I got:
in program terminal:
<<<<<<<<<<<<<<<<<<<<<<<<<<
&"warning: GDB: failed to set controlling terminal: Operation not permitted\n"


and in application window:
<<<<<<<<<<<<<<<<<<<<<<<<<<
Couldn't inject exception handler breakpoint - no bytecode match foundwarning: Could not load shared library symbols for linux-gate.so.1.\nDo you need \"set solib-search-path\" or \"set sysroot\

[Thread debugging using libthread_db enabled]
Using host libthread_db library \"/usr/lib/libthread_db.so.1\".


And it seems that breakpoint works but no indication of that in edit window, then I press F5 and it runs the statement on which i have the breakpoint (printing Hello World in terminal). 

If I run monodevelop with sudo everything the same.

**Comment by aBothe** [comment]
So, in fact, it does work. That first message can't be omitted for unknown reasons.
The second one - I told you above. The indication issue tends to appear, but in general, those aren't there permanently..just step through or double-click the upper-most call stack entry.

**Comment by service-trade** [comment]
DDD works well with either project and GDB from command line too

**Comment by aBothe** [comment]
DDD?

**Comment by service-trade** [comment]
Data Display Debugger -- frontend to GDB

**Comment by service-trade** [comment]
I don't get this message with monodevelop installed thru pacman

**Comment by aBothe** [comment]
So here we go then.

**Comment by service-trade** [comment]
Then I go to write own IDE for D :)

**Comment by aBothe** [comment]
Enjoy! ;)
Still, it's not garantueed that the debugger works on each setup - but under common circumstances it should run - as it's doing so atm. Even the fact that it's not displaying the point where it breaks may related to other things - is it (not) working in C projects as well?

**Comment by service-trade** [comment]
Tried to set up SublimeText + SublimeTextGDB and getting here simular error 
GDB: Failed to set controlling terminal: Inappropriate ioctl for device
but it works anyway

**Comment by service-trade** [comment]
Hmm your assembly of mono+monodevelop works on D project!

**Comment by service-trade** [comment]
On C HelloWorld I see behavour that I wrote above.
But on D I see yellow highlight and it works fine with F10 
Sorry my bad ;)

**Comment by aBothe** [comment]
Ah okay, nice then :) - Time to close this report then?

**Comment by service-trade** [comment]
So trouble in my mono assembly from archlinux repository as I thinking above.
Sure close ;) Thanks!

**Comment by alexhairyman** [comment]
I'm trying to follow this comment thread, what was the final solution? downloading the GDb.D from the link? I've tried using monodevelop 4.2.4 (from your website), 4.2.3 (from AUR), and 4.2.2 (from package manager), and I get the same could not load linux-gate.so.1 each time (on 32 bit arch linux)

I'm sure the answer is here, I just don't know what it is exactly.

**Comment by aBothe** [comment]
it's a n error inside the gdb.d addin
