### ISSUE TITLE
Xamarin studio support

### ISSUE THREAD

**Issue by Computermatronic** [llucenic/MonoDevelop.Debugger.Gdb.D#5]
I am currently running Xamarin studio 5.1 and when i attempted to install, I encountered an error saying i have missing dependencies
MonoDevelop.Core v4.0, found v5.1
MonoDevelop.Ide v4.0, found v5.1

**Comment by llucenic** [comment]
Hi, is this issue still actual?

**Comment by aBothe** [comment]
Unlikely, thanks for noticing it. :)
