### ISSUE TITLE
How to set as preferred debugger.

### ISSUE THREAD

**Issue by michaelc37** [llucenic/MonoDevelop.Debugger.Gdb.D#6]
It seems MD got rid of the option to set a preferred debugger?
https://github.com/mono/monodevelop/commit/f0e931b95241293dce4527b0f1c2211090cbd58d

Is there  another way select gdb.d as the debugger?
How are you guys using it?

**Comment by aBothe** [comment]
Despite it's still under development (whereas you probably might spend time & effort into it? :P), you then disable the normal gdb debugger to get Mono-D's to be preferred. Perhaps there's some tweak or API hack that has to be used to show up the debugger selection again - wheras..there still is an 'Execute with'-menu in my latest bleeding edge-build of MonoDevelop
![bildschirmfoto - 18 12 2014 - 12 49 32](https://cloud.githubusercontent.com/assets/1143073/5487662/75bdee6c-86b4-11e4-95ff-aa86f487ca8d.png)

**Comment by michaelc37** [comment]
Thanks,

I think this has now made it into stable versions and i discovered this after installing monodevelop from their own ppa ( http://www.monodevelop.com/download/linux/#debian-ubuntu-and-derivatives ).

Having to go to the menu to use execute with gets annoying pretty quickly, 
but I didn't think of disabling the normal gdb debugger, I guess that is the only option for now.

Thanks again.

**Comment by michaelc37** [comment]
Just got a update from @DavidKarlas, https://github.com/mono/monodevelop/commit/f0e931b95241293dce4527b0f1c2211090cbd58d

"Sorry for this late response...
What you should do is first update Gdb and/or Gdb.D to use new "SessionFactory". Because current implementation of session creation is inherited from IDebuggerEngine but it should be from DebuggerEngineBackend.

Once this is changed(I don't think it's more then weekend of work) you should implement IsDefaultDebugger which you decide based on ExecutionCommand or you can just simply return true if you have good filter in CanDebugCommand to filter out just D programs."

**Comment by DavidKarlas** [comment]
Ok... So what I suggest you to do is this...

1st create class DExecutionCommand and inherit NativeExecutionCommand(or directly ExecutionCommand). Then in [DProject.cs](https://github.com/aBothe/Mono-D/blob/master/MonoDevelop.DBinding/Projects/DProject.cs#L358) return this DExecutionCommand so you can use below code in implementation of DebuggerEngineBackend.

``` csharp
public override bool CanDebugCommand (ExecutionCommand command)
{
    var cmd = command as DExecutionCommand;
    return cmd != null;
}

public override bool IsDefaultDebugger (ExecutionCommand cmd)
{
    return true;//This will only be called if CanDebugCommand is true...
}
```

I hope I was clear... ask any question if something is not clear...

**Comment by aBothe** [comment]
Thanks for the hints, this issue should be solved then.

**Comment by llucenic** [comment]
Hi Alex, is it solved by now?

**Comment by aBothe** [comment]
Indeed, this has been solved now.
